### ISSUE TITLE
iknowpy: Certain characters cause a shift in word and sentence boundaries

### ISSUE THREAD

**Issue by ISC-SDE** [intersystems/iknow#64]
The input below contains some Greek characters which seem to mess up the detection of word boundaries. Boundaries (spaces) appear at the wrong positions, causing splitting and incomplete words. This is especially clear at the end of the sentence: the first 3 characters of the second sentence become part of the first sentence. The shift continues until the end of the input file.
The input file is UTF-8 encoded, as required.

input:
Syloïde blijkt een vergelijkbaar of zelfs groter effect te hebben op sommige parameters (bijv. 𝑎2, 𝑎3, 1 𝑡1 en 1 𝑡3) van de compressievergelijking. Dit vergelijkbare effect wordt echter vaak alleen bereikt bij een hogere concentratie Syloid in vergelijking met magnesiumstearaat.

output:
S1: Syloïde blijkt een vergelijkbaar of zelfs groter effect te hebben op sommige parameters (bijv. 𝑎2, 3, 1 𝑡1 en 1 3) van de om ressievergelijking. Dit
S2: ver elijkbare effect wor t ech er vaa < all> en ber ikt bij een hog re concentratie Syloid in ergelijking met mag esiumstearaat.

**Comment by JosDenysGitHub** [comment]
The source of this problem is the use of unicode chars that exceed the 2byte maximum: 
'𝑎' = U+1D44E
Python sees this as a single symbol, but when it is transferred into the engine, it is converted to a surrogate pair : 
UCS2 : 35 D8 4E DC
The engine counts 2 symbols, and that generates a shift in text offset counting, the values that are used to reconstruct the Literal representation.
As of version 1.0.9, such symbols are detected, and the text offset is corrected for Python text representation.

**Comment by ISC-SDE** [comment]
The issue is solved. Thank you!
