### ISSUE TITLE
handleCSV.py script removes certain multi-lexreps previously expanded by DELVE

### ISSUE THREAD

**Issue by makorin0315** [intersystems/iknow#96]
I came across a situation where the handleCSV.py script does not restore multi-lexreps expanded by the DELVE code.

Original line in JP_jp_lexreps.csv:

;;(を手に取|を手にと);;JPParticleWO;-;JPVerbOther;Join;Join;

lexreps.csv generated by DELVE for the same line reads as follows:

/**** Rewritten by DELVE, ;;を手に取;;JPParticleWO;-;JPVerbOther;Join;Join;
;;を手に取;;JPParticleWO;Lit_を;-;JPVerbOther;Join;Join
/**** Rewritten by DELVE, ;;を手にと;;JPParticleWO;-;JPVerbOther;Join;Join;
;;を手にと;;JPParticleWO;Lit_を;-;JPVerbOther;Join;Join
/* Expanded previously by DELVE....;;(を手に取|を手にと);;JPParticleWO;-;JPVerbOther;Join;Join;

lexreps.csv after running handleCSV.py:
=> lexreps associated with the line no longer exists

I've checked several other expanded multi-lexrep entries, but so far this seems to be the only instance with this issue.

**Comment by JosDenysGitHub** [comment]
Hi Masako,

The problem is not the original line, but the next line in JP_jp_lexreps.csv:

;;(を手に取|を手にと); - 05-may-2014-mno;JPParticleWO;-;JPVerbOther;Join;Join;
;;(**を手に取り**|**を手に取り**); - 26-jun-2015-mno;JPParticleWO;-;JPVerbNoun;Join;Join;Join;

As you can see, the second line has twice the same entry ("を手に取り"), making the "rewrite" process think that 2 lines need to be removed, but the literal insert process is smart enough to see that both are the same, and it only writes one line:

/**** Rewritten by DELVE, ;;を手に取り;;JPParticleWO;-;JPVerbNoun;Join;Join;Join;
;;を手に取り;;JPParticleWO;Lit_を;-;JPVerbNoun;Join;Join;Join
/* Expanded previously by DELVE....;;(を手に取り|を手に取り);;JPParticleWO;-;JPVerbNoun;Join;Join;Join;

That explains why the line before (;;(を手に取|を手にと); - 05-may-2014-mno;JPParticleWO;-;JPVerbOther;Join;Join;) disappears.

I propose we can consider this a modeling error ?
I could add a "warning" in cases the "|" operator generates equal entries...

Jos.

**Comment by makorin0315** [comment]
Thanks for looking into it, @JosDenysGitHub. 
Yes, that explains my observation. the next line should have been (を手に取り|を手にとり) instead. I think a warning would be useful - where would you add it? In HandleCSV.py or when compiling the language model?

**Comment by JosDenysGitHub** [comment]
I added a test to see if equal alternatives are present (https://github.com/intersystems/iknow/commit/ba3bcfcff7cda966414a0e32677163214fcb93e1), if so, the processing stops. I also fixed the lexreps.csv file. I tested all languages, only Japanese had this flaw...

**Comment by makorin0315** [comment]
Due to multiple ways a single word can be written, multi-lexreps are abundant in Japanese, making it more likely to include such errors. I'm glad that it's not a problem in other languages. 

I see that the language compiler halts the process now, with information about the problematic lexrep. This solution is fine, as I'm likely the only person who'll use the handleCSV.py script. Thanks for the quick turnaround!
